// <auto-generated />
using System;
using BulkRename.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BulkRename.Migrations
{
    [DbContext(typeof(BulkRenameContext))]
    [Migration("20200726125210_CreateTableSeason")]
    partial class CreateTableSeason
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BulkRename.Shared.Models.Entities.Season", b =>
                {
                    b.Property<Guid>("SeasonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SsnNumberString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SsnSerieID_FK")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SeasonID");

                    b.HasIndex("SsnSerieID_FK");

                    b.ToTable("SeasonItems");
                });

            modelBuilder.Entity("BulkRename.Shared.Models.Entities.Serie", b =>
                {
                    b.Property<Guid>("SerieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SerieID");

                    b.ToTable("SerieItems");
                });

            modelBuilder.Entity("BulkRename.Shared.Models.Entities.Season", b =>
                {
                    b.HasOne("BulkRename.Shared.Models.Entities.Serie", "Serie")
                        .WithMany()
                        .HasForeignKey("SsnSerieID_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
