// <auto-generated />
using System;
using BulkRename.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulkRename.Migrations
{
    [DbContext(typeof(BulkRenameContext))]
    [Migration("20260216185204_CreateMoreFieldsAboutFileInfo")]
    partial class CreateMoreFieldsAboutFileInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulkRename.Models.Entities.Episode", b =>
                {
                    b.Property<Guid>("EpisodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("EpsEpisodeFileSizeInMb")
                        .HasColumnType("float");

                    b.Property<string>("EpsEpisodeNewName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EpsEpisodeOriginalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EpsFileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EpsLastWriteTimeTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EpsNumberString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EpsSeasonID_FK")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EpisodeID");

                    b.HasIndex("EpsSeasonID_FK");

                    b.ToTable("EpisodeItems");
                });

            modelBuilder.Entity("BulkRename.Models.Entities.RenamingSession", b =>
                {
                    b.Property<Guid>("RenamingSessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RenExecutingDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RenRenamingSessionIsOk")
                        .HasColumnType("bit");

                    b.HasKey("RenamingSessionID");

                    b.ToTable("RenamingSessionItems");
                });

            modelBuilder.Entity("BulkRename.Models.Entities.RenamingSessionToEpisode", b =>
                {
                    b.Property<Guid>("RenamingSessionToEpisodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RseEpisodeID_FK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RseRenamingSessionID_FK")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RenamingSessionToEpisodeID");

                    b.HasIndex("RseEpisodeID_FK");

                    b.HasIndex("RseRenamingSessionID_FK");

                    b.ToTable("RenamingSessionToEpisodeItems");
                });

            modelBuilder.Entity("BulkRename.Models.Entities.Season", b =>
                {
                    b.Property<Guid>("SeasonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SsnNumberString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SsnSerieID_FK")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SeasonID");

                    b.HasIndex("SsnSerieID_FK");

                    b.ToTable("SeasonItems");
                });

            modelBuilder.Entity("BulkRename.Models.Entities.Serie", b =>
                {
                    b.Property<Guid>("SerieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SerieID");

                    b.ToTable("SerieItems");
                });

            modelBuilder.Entity("BulkRename.Models.Entities.Episode", b =>
                {
                    b.HasOne("BulkRename.Models.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("EpsSeasonID_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("BulkRename.Models.Entities.RenamingSessionToEpisode", b =>
                {
                    b.HasOne("BulkRename.Models.Entities.Episode", "Episode")
                        .WithMany()
                        .HasForeignKey("RseEpisodeID_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BulkRename.Models.Entities.RenamingSession", "RenamingSession")
                        .WithMany()
                        .HasForeignKey("RseRenamingSessionID_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");

                    b.Navigation("RenamingSession");
                });

            modelBuilder.Entity("BulkRename.Models.Entities.Season", b =>
                {
                    b.HasOne("BulkRename.Models.Entities.Serie", "Serie")
                        .WithMany()
                        .HasForeignKey("SsnSerieID_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Serie");
                });
#pragma warning restore 612, 618
        }
    }
}
